### ISSUE TITLE
Pagination/Filters - supposed to be visible on Activity/Connection ?

### ISSUE THREAD

**Issue by SjonHortensius** [sosedoff/pgweb#187]
Because the #pagination shows when switching from the Rows tab; but is hidden when switching from any of the other tabs (like Structure / Indexes).

I'm not sure what the correct behavior is, it might make sense for the Activity tab to have pagination but not filtering

**Comment by sosedoff** [comment]
Pagination/Filters are only intended for browser view (aka rows). There's no supporting functionality for other pages in the backend so the correct behavior is not to show them on any other pages. If you wish to have pagination on activity page, feel free to submit PR. Closing for now since its not a top priority nor requires any special attention.

**Comment by SjonHortensius** [comment]
Please re-open; this is a bug-report. The pagination on the activities page is not hidden after switching from the Rows tab

**Comment by sosedoff** [comment]
Ah, misunderstood your report. Indeed, its a bug.

**Comment by sosedoff** [comment]
Fixed in master, will be available in the laster release.
