### ISSUE TITLE
Workbench features

### ISSUE THREAD

**Issue by marks** [sosedoff/pgweb#188]
Would love to see some features around saving the SQL query, schema, results, etc. to disk.

**Comment by sosedoff** [comment]
yeah, i was thinking about adding a database (sqlite) to store settings and other db-related stuff (mostly queries). not sure when i get to implement that.

**Comment by akarki15** [comment]
Syntax completion would be awesome too!

**Comment by Vonatzki** [comment]
Label-able SQL query tabs would be rad, too :)

(I'm coming from [Postage](https://github.com/workflowproducts/postage/), which is almost a viable pgadmin substitute but then the developers decided to lessen their support due to failure to monetize the project. It's worth checking out and see if some of its features can be incorporated in pgweb.)

**Comment by Vonatzki** [comment]
Another feature that would be nice is convenient copy pasting of selected portions of any tables being displayed in the app.

As of 0.9.8, highlighting desired portion of a table is tricky and often require highlighting the whole table instead.

**Comment by sosedoff** [comment]
This is a super stale issue, im just going to close it since there were a lot of new features added since 2017 :)
