### ISSUE TITLE
Support the ouput of query result in pretty json format

### ISSUE THREAD

**Issue by maksm90** [sosedoff/pgweb#249]
Hi!

Thanks for the development of great web client to postgres. But my colleagues and I would like to see the feature of printing query result in the result window in formats other than tabular (e.g. structured indented json).

How is this possible? Can I join the project to implement this feature?

**Comment by sosedoff** [comment]
There's already a JSON export button available on the custom query page. Is that what you're looking for?

**Comment by maksm90** [comment]
Do you mean the button that downloads a query result?
I propose the feature of printing result on window in specified format so that it can be copy-pasted to somewhere. Moreover, this format should be pretty to look at.

**Comment by Garbee** [comment]
I think a "Copy as JSON" button is quite doable for modern browsers. But, a JSON *view* I feel is not incredibly useful to most users.

**Comment by sosedoff** [comment]
Im closing this issue since there's a very little need for this specific use case. I've just added a new feature to allow downloading query results as a formatted JSON file (see master), that should be enough to get by. If that does not suit your needs, feel free to submit a patch, i'd be happy to review and merge.
