### ISSUE TITLE
Add wiki entry for running behind nginx

### ISSUE THREAD

**Issue by sosedoff** [sosedoff/pgweb#263]

**Comment by Garbee** [comment]
My [old config post](https://github.com/sosedoff/pgweb/issues/84#issuecomment-96741961) is still working for me. But as comments later brought up do remember to add a note about using basic authentication to protect the system. Since once you log in anyone can hit the URL and get DB access unless you have auth in place.

**Comment by sosedoff** [comment]
@Garbee yeah i get that, but i'd rather have an official manual on hand for all the newcomers to follow. Since i don't use pgweb behind nginx i'll just go over all the manual steps myself, but if you have any configuration samples (excluding already mentioned post) you're welcome to reference them here or send to my email directly. As for the basic app, pgweb has the auth feature, so i'm not sure why people don't use it.

**Comment by Garbee** [comment]
I don't use the built in auth since that means I need to pull in a user/pass to yet another place on the system. Using nginx's basic auth I can reference my existing accounts in the `.htpasswd` file for nginx which I use with other protected services as well.

If pgweb could pull in the existing file to authorize access then I'd be all for it. But as I see the options now in the help explanation it doesn't pull in an existing access file.
