### ISSUE TITLE
Can support CockroachDB?

### ISSUE THREAD

**Issue by skyformat99** [sosedoff/pgweb#273]
Great project, :+1: 
But I tried to use it, I connected CockroachDB, but I couldn't connected .
Can support CockroachDB?    https://www.cockroachlabs.com/
thanks.

**Comment by sosedoff** [comment]
Thank you. There was another issue #235 related to the CockroachDB, but
just to reiterate on it - no pgweb does not support CockroachDB at this time
since it has a bunch of pg-specific queries under the hook. It is possible to make
it work, but that would require a serious effort. I dont use CockroachDB myself so
i cant really say if the support will be available in the future.
