### ISSUE TITLE
Rows view with jsonb field is slow

### ISSUE THREAD

**Issue by wow-sweetlie** [sosedoff/pgweb#283]
I'm not sur if it's json or just jsonb, but I have table with jsonb field that can represent up to 1MB of json (in his text form). The rendering of row view takes from few seconds to few minutes, the most larger the field is the more slow is the rendering.

**Comment by sosedoff** [comment]
How many rows are we talking about?

**Comment by wow-sweetlie** [comment]
I didn't see if we can set the pagintion to a lower number, than the default, so it's actually 100 row displayed for a total of 15000 row on my dev database, about 15 million on production if it matter, but didn't try  to render it in pgweb installed on my production server.

**Comment by sosedoff** [comment]
Im almost 100% sure the slowness is due to the DOM-building. 1MB per row is a lot of data to be displayed in html. When you click on the table on the sidebar, you'll see a new API query in the pgweb's log:

```
[GIN] 2017/10/02 - 10:02:53 | 200 |   17.092465ms |       127.0.0.1 |  GET     /api/tables/public.items/rows
```

That will give you a rough idea on how long did it actually take to process the request. If you see the request duration is very large - let me know so we can troubleshoot this.

**Comment by wow-sweetlie** [comment]
I can't test for a long moment, you can probably close the issue meantime  I'll come back when I'll have information to report back to you.

**Comment by sosedoff** [comment]
any tables that contain large blobs of text or other data will result in UI slowness, there's not much that could be done in the current pgweb version. closing for now.
