### ISSUE TITLE
Add export in SQL

### ISSUE THREAD

**Issue by varp** [sosedoff/pgweb#293]
It must be useful for moving the part of data of tables to the different DB engines

**Comment by sosedoff** [comment]
Raw SQL export (whole db/single table) is already implemented and available in 0.9.9

**Comment by varp** [comment]
But not on the SQL results. I have tables with more than dozen millions of rows and sometimes I need a couple of rows from production Postgres DB to a developer MySQL table and the simplest way to do it is just to copy/paste and execute SQL

**Comment by sosedoff** [comment]
How would this feature work on the subset of table data? My guess is that you can always write a custom sql query and export the resulting data as csv, then import that file using postgres csv import feature.

I don't think this feature request worth implementing (from my point of view) since it's based on a very specific use case.  If you'd like to make it happen - send some code ;)
