### ISSUE TITLE
Specify CA/Client certs for verify-full mode

### ISSUE THREAD

**Issue by antoniomo** [sosedoff/pgweb#360]
Related to issue #228 but that one was closed.

Adding more information:

when testing with CockroachDB 2.0 (which, AFAIK, should support pgweb) on secure mode, I can't get a self signed root cert to work:

```
pgweb --url postgres://root@localhost:26257/testdb?sslmode=verify-full&sslcert=client.root.crt&sslkey=client.root.key&sslrootcert=ca.crt

Pgweb v0.9.12 (git: 9af721176bf7b41366f0de8251fff0b47da8fce3)
Connecting to server...
Error: x509: certificate signed by unknown authority
```

**Comment by Garbee** [comment]
CockroachDB is not supported by pgweb. There was [a PR to add it](https://github.com/sosedoff/pgweb/pull/351) but the author closed it until they added test setup so tests get executed on that engine too.

**Comment by antoniomo** [comment]
I see! However nothing on that PR points to a different treatment of the certificates on the url string, so I think the author used it without ssl. Are self signed certificates supported by pgweb in vanilla postgres?

**Comment by sosedoff** [comment]
Im closing this issue for now since there's not much i can help with at this time.

Pgweb uses https://github.com/lib/pq to connect to postgres, so if something regarding certs/CA stuff does not work i'd definitely look into that repo.

Pgweb 0.10.0 is finally out with a bunch of updated deps (including lib/pq one) so give it a try.
