### ISSUE TITLE
Can't seem to access tables not on "public"

### ISSUE THREAD

**Issue by ric2z** [sosedoff/pgweb#383]
Hi there,

I recently started a new instance on Heroku, but I'm not able to access tables under schemas other than `public`. For example, I'm trying to access a table named `event` on a schema named `blanket`, but I get this error on the **Rows** tab:

> **ERROR: pq: relation "public.event" does not exist**

Has anyone seen this issue before? Happy to share more information if needed.

Thanks in advance.

**Comment by sosedoff** [comment]
Which version of pgweb are you using ?

**Comment by ric2z** [comment]
@sosedoff I used the "Deploy to Heroku" button, so I'm guessing I'm on the latest version.

**Comment by sosedoff** [comment]
I'll have a look

**Comment by sosedoff** [comment]
@ric2z  is this still an issue for you? i tried to replicate your setup, but i had no problem seeing different schemas in my test db on heroku.

**Comment by ttencate** [comment]
Same here:

    Pgweb v0.10.0 (git: 54da27ef70b1d2ae9297cc5ea65158148b36107d)

The schema and its tables do appear in the left sidebar, but if I click one of them, instead of seeing the table's contents, I get an error:

> ERROR: pq: relation "public.tablename" does not exist

Indeed it doesn't, because `tablename` is not in the `public` schema.

![2018-12-12-144907_1082x665_scrot](https://user-images.githubusercontent.com/90930/49873856-2bf84e00-fe1d-11e8-9c22-239e35a6d732.png)

**Comment by sosedoff** [comment]
Finally was able to replicate the issue on my machine. There's a bug with row estimation query that causes this error. Will fix.

**Comment by sosedoff** [comment]
This issue has been fixed, please upgrade to 0.11.0
