### ISSUE TITLE
Resize or toggle height of result

### ISSUE THREAD

**Issue by beeing** [sosedoff/pgweb#483]
Currently the result pane taking up quite a fair bit of space and in fact most of the time we focusing on the query.

Perhaps to feature to allow change of height or close it until next query runs.

Oh, btw, I did noticed there's no time taken in the results pane.

Would be great add-on for those who debugging queries and comparing the time taken to run those queries.

Thanks!

**Comment by sosedoff** [comment]
Re 1) - No UI changes are planned for the time being
Re 2) Timing queries is a bit tricky since we not only execute queries on the remote server, but also decode incoming data, and render that on the frontend. I understand that you want to have real timing info - unfortunately pgweb will not be able to provide that. If you would like to contribute timing codebase - please do!
