### ISSUE TITLE
Prefilled connection data

### ISSUE THREAD

**Issue by Int32Overflow** [sosedoff/pgweb#490]
How to set default values for connection data (such as host, username, database, ...) on the connection data dialog in sessions mode?

**Comment by sosedoff** [comment]
There's no way to set default values for connections in session mode due to security concerns, however if your environment is private and trusted (ie behind a firewall or something like that) you can create a few different bookmarks (https://github.com/sosedoff/pgweb/wiki/Server-Connection-Bookmarks) . When selecting a bookmark all the connection info is pre-filled.
