### ISSUE TITLE
Running Pgweb on ECS Fargate

### ISSUE THREAD

**Issue by brucedvgw** [sosedoff/pgweb#495]
Is it possible to run pgweb on ECS Fargate with connectivity to a Postgres DB?

I have tried to get pgweb up and running with the `sosedoff/pgweb` image, however it fails to resolve the host name of the database. I assume this is related to pgweb listening on localhost?

Has anyone been able to deploy it to ECS Fargate?

**Comment by sosedoff** [comment]
I've run pgweb on ecs fargate so its definitely possible. Your issue is not clear, if you want me to troubleshoot you need to provide at least something, like ecs task definition or a command. You mention it fails to resolve the db hostname - it has nothing to do with pgweb and everything with how you're running the containers, so some context is a must in order to figure out your setup. 

basically the ecs setup boils down to the following:

- make sure your pgweb task runs in the same vpc as the postgres database (presumably rds) in order to use the internal dns
- postgres database security groups allow access from the pgweb ecs container
- pgweb task container has outbout rules to access the rds instance/ postgres database

**Comment by brucedvgw** [comment]
Thanks @sosedoff, it turns out that I need to add the RDS security group to the outbound ECS Task security group. Thanks for the pointer!
