### ISSUE TITLE
Cannot filter by empty string

### ISSUE THREAD

**Issue by AlmogBaku** [sosedoff/pgweb#526]
Currently, there's no way to filter by an empty string(not null) value

**Comment by sosedoff** [comment]
I just checked this and you're right - no way to filter by an empty string. I don't really think this is a deal breaker, since filtering is supposed to apply to certain values in most cases (other cases being `null`s). You're 100% getting an error if filter is not provided, so it's an expected behavior.

We could introduce a `IS BLANK` filter in the dropdown so you can explicitly filter by an empty string. I don't have any capacity to work on this feature, so if you want to have this particular filter - please open up a PR, i'll review and merge it if it does not break any existing functionality.
